client_id = "bhxnw1a3ulxyatu7psbv"
client_secret = "rGSRw+6Tjrw2hXhJBFw2gwR8Rpn/a+dbp8C7A7l1/6Y"
token_url = "https://auth.listrak.com/OAuth2/Token"

storageCreds = "DefaultEndpointsProtocol=https;AccountName=analystdatalakedlsdtc;AccountKey=zhDRuMdIfKF8wzSYDQ76ElYYcw/O10lcv02TsysowoTb4AHyDdwFE4dSWNk+5JUfo7VgY7FQ7tf0bUemZ8/Hjw==;EndpointSuffix=core.windows.net"

token = 'dapi72c0d16ad7100a267de91425b8a864ee'
instance = "https://eastus2.azuredatabricks.net/"


softBounces = ['DNS Failure', 'Transient Failure', 'Auto Reply', 'General Soft Bounce',
               'General Bounce', 'General Mail Block', 'Relay Denied', 'Spam Detected',
               'Mailbox Full', None, 'None']

microsoftDomains = ['hotmail.com',
 'msn.com',
 'outlook.com',
 'homail.com',
 'hotamail.com',
 'hotamil.com',
 'hotmai.com',
 'hotmail.be',
 'hotmail.ch',
 'hotmail.co.jp',
 'hotmail.co.uk',
 'hotmail.com',
 'hotmail.com.ar',
 'hotmail.com.br',
 'hotmail.com.tr',
 'hotmail.de',
 'hotmail.dk',
 'hotmail.es',
 'hotmail.fr',
 'hotmail.it',
 'hotmail.lu',
 'hotmail.nl',
 'hotmail.no',
 'hotmail.pt',
 'hotmail.se',
 'hotmeil.com',
 'live.at',
 'live.be',
 'live.ca',
 'live.cl',
 'live.cn',
 'live.co.uk',
 'live.co.za',
 'live.com',
 'live.com.ar',
 'live.com.au',
 'live.com.mx',
 'live.com.pt',
 'live.de',
 'live.dk',
 'live.fr',
 'live.it',
 'live.jp',
 'live.nl',
 'live.no',
 'live.ru',
 'live.se',
 'microsoft.com',
 'microsoftnetwork.com',
 'msn.ca',
 'msn.com',
 'msn.de',
 'msn.fr',
 'msn.it',
 'msnbc.com',
 'otmail.com',
 'webtv.net',
 'windowslive.com']
gmailDomains = ['gmail.com', 'googlemail.com']
yahooDomains = ['geocities.com',
 'kimo.com',
 'maktoob.com',
 'oddpost.com',
 'yahoo.ca',
 'yahoo.cl',
 'yahoo.co.id',
 'yahoo.co.in',
 'yahoo.co.kr',
 'yahoo.co.nz',
 'yahoo.co.th',
 'yahoo.co.uk',
 'yahoo.com',
 'yahoo.com.ar',
 'yahoo.com.au',
 'yahoo.com.br',
 'yahoo.com.cn',
 'yahoo.com.co',
 'yahoo.com.hk',
 'yahoo.com.mx',
 'yahoo.com.my',
 'yahoo.com.pe',
 'yahoo.com.ph',
 'yahoo.com.sg',
 'yahoo.com.tr',
 'yahoo.com.tw',
 'yahoo.com.ve',
 'yahoo.com.vn',
 'yahoo.de',
 'yahoo.dk',
 'yahoo.es',
 'yahoo.fr',
 'yahoo.gr',
 'yahoo.ie',
 'yahoo.in',
 'yahoo.it',
 'yahoo.no',
 'yahoo.pl',
 'yahoo.ro',
 'yahoo.se',
 'yahoomail.com',
 'yahooxtra.co.nz',
 'ymail.com',
 'y7mail.com']
aolDomains = ['aim.com',
 'aol.com',
 'compuserve.com',
 'cs.com',
 'netscape.com',
 'netscape.net',
 'wmconnect.com']

listDict = {
    'yccUK': 353978,
    'marmot': 353979,
    'graco': 354015,
    'exofficio': 353969,
    'coleman': 275481,
    'calphalon': 354013,
    'food': 354386,
    'yccUS': 353977,
    'babyjogger': 354012,
    'contigo': 354014,
    'dymo': 354209,
    'exofficioPP': 355536,
    'foodsaver': 354386,
    'holmes': 354387,
    'marmotPP':355429,
    'parker': 354211,
    'yankeeFrance': 354116,
    'yankeeItaly': 354117,
    'babyjoggerA': 354306,
    'colemanA': 275504,
    'calphalonA': 354304,
    'exofficioA': 354276,
    'foodsaverA': 354434,
    'gracoA': 354305,
    'yccA': 355069,
    'rubbermaid': 354215,
    'crockpot': 354391,
    'mrcoffee': 354390,
    'oster': 354458,
    'sunbeam': 354457,
    'freshpreserve': 354227,
    'yankeeGermany': 354118,
    'margaritaville': 354388,
    'marmotA':354254,
    'yankeeUKA': 355360
}
